# 基本影像過濾器 - 卷積運算
---

### 第一步、載入Python套件

In [11]:
# 載入套件
import numpy as np
import cv2 as cv

### 第二步、讀取資料夾中的影像，這裡以Lenna.png為例

In [12]:
# 從圖檔讀取影像像素值矩陣
# 函式輸出入 => 影像像素值矩陣 = cv.imread(圖片路徑)
img = cv.imread('./img/Lenna.png')

### 第三步、自定義卷積運算之核函數
此範例為平滑化與銳利化核函數定義方式，自定義可嘗試不同尺寸與數值

In [13]:
# 定義平滑化核函數，格式必須使用numpy二維陣列
kernel_smoothed = np.array([[0.04, 0.04, 0.04, 0.04, 0.04],
                            [0.04, 0.04, 0.04, 0.04, 0.04],
                            [0.04, 0.04, 0.04, 0.04, 0.04],
                            [0.04, 0.04, 0.04, 0.04, 0.04],
                            [0.04, 0.04, 0.04, 0.04, 0.04]])

# 定義銳利化核函數，格式必須使用numpy二維陣列
kernel_sharpened = np.array([[ 0, -1,  0],
                             [-1,  4, -1],
                             [ 0, -1,  0]])

# 顯示核函數內容二維陣列
print("Kernel smoothed: \n", kernel_smoothed)
print("Kernel sharpened: \n", kernel_sharpened)

Kernel smoothed: 
 [[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]
Kernel sharpened: 
 [[ 0 -1  0]
 [-1  4 -1]
 [ 0 -1  0]]


### 第四步、依據自定義核函數進行卷積運算

In [14]:
# 將原圖進行平滑化卷積運算
# 函式輸出入 => 輸出影像 = cv.inRange(輸入影像, 輸出影像格式, 核函數)
img_smoothed=cv.filter2D(img, ddepth=cv.CV_8U,kernel=kernel_smoothed)

# 將原圖進行銳利化卷積運算
# 函式輸出入 => 輸出影像 = cv.inRange(輸入影像, 輸出影像格式, 核函數)
img_sharpened=cv.filter2D(img, ddepth=cv.CV_8U,kernel=kernel_sharpened)

### 第五步、開啟視窗並將影像顯示出來，按任意鍵將視窗關閉

In [15]:
# 顯示原始影像與二值化影像
# 函式輸出入 => cv.imshow(視窗名稱, 影像矩陣)
cv.imshow("Original Lenna", img)
cv.imshow("Smoothed Lenna", img_smoothed)
cv.imshow("Sharpened Lenna", img_sharpened)

# 暫停程式並在按下任意鍵後結束暫停
# 函式輸出入 => 按鍵字元編碼 = cv.waitKey(停等時間單位毫秒)
cv.waitKey(0)

# 關閉所有OpenCV的視窗
# 函式輸出入 => cv.destroyAllWindows()
cv.destroyAllWindows()