# OpenCV-膨脹 (Dilation)

## key 範例

<table>
    <tr>
        <td><img src="./img/key.jpg"></td>
        <td> <img src="./img/key_with_Salt_noise.png"></td>
    </tr>
</table>

In [1]:
#載入模組
import cv2 as cv
import numpy as np

In [4]:
img_key = cv.imread('./img/key.jpg')#讀取影像
img_key = cv.imread('./img/key_with_Salt_noise.png')#讀取影像

In [5]:
kernel = np.ones((3,3),np.float64)/25
print(kernel)


dilation_key = cv.dilate(img_key,kernel,iterations = 1)
dilation_3key = cv.dilate(img_key,kernel,iterations = 3)


cv.imshow('Ori_key',img_key)
cv.imshow('Dilation_key',dilation_key)
cv.imshow('Dilation_3key',dilation_3key)


cv.waitKey(0)
cv.destroyAllWindows()

[[0.04 0.04 0.04]
 [0.04 0.04 0.04]
 [0.04 0.04 0.04]]
