# OpenCV-膨脹 (Dilation)

## lenna 範例

In [7]:
#載入模組
import cv2 as cv
import numpy as np

In [8]:
img_lenna = cv.imread('./img/lenna.png')
#img_lenna = cv.imread('./img/lenna_with_Salt-and-pepper_noise.png')#讀取影像

In [9]:
kernel = np.ones((3,3),np.float32)/25
print(kernel)


dilation_lenna = cv.dilate(img_lenna,kernel,iterations = 1)
dilation_3lenna = cv.dilate(img_lenna,kernel,iterations = 3)


cv.imshow('Ori_lenna',img_lenna)
cv.imshow('Dilation_lenna',dilation_lenna)
cv.imshow('Dilation_3lenna',dilation_3lenna)


cv.waitKey(0)
cv.destroyAllWindows()

[[0.04 0.04 0.04]
 [0.04 0.04 0.04]
 [0.04 0.04 0.04]]
