# OpenCV-膨脹 (Dilation)

## J範例

<table>
    <tr>
        <td><img src="./img/J_with_white_noise.png"></td>
        <td> <img src="./img/J_with_black_noise.png"></td>
    </tr>
</table>

In [10]:
#載入模組
import cv2 as cv
import numpy as np

In [11]:
img_j = cv.imread('./img/j.png')#讀取影像
img_j = cv.imread('./img/geometry.png')#讀取影像
#img_j = cv.imread('./img/j_with_white_noise.png')#讀取影像
#img_j = cv.imread('./img/j_with_black_noise.png')#讀取影像

In [15]:
#要是用任何影像過濾都需要先設定我們要的kernel參數，這邊選用的是5*5的kernel，也可以調整為3*3或是7*7做比較
kernel = np.ones((5,5),np.float32)/25
print("kernel")
print(kernel)


#使用opencv內建膨脹函式做影像處理
dilation_j = cv.dilate(img_j,kernel,iterations = 1)
#dilation_3j = cv.dilate(img_j,kernel,iterations = 1)
dilation_3j = cv.erode(dilation_j,kernel,iterations = 1)

#dst_img=cv.dilate(src_img,kernel,iteration)
#dst_img:輸出影像
#src_img:輸入影像
#kernel:使用的核
#iterations:跌代次數


#顯示影像處理結果
cv.imshow('Ori_j',img_j)
cv.imshow('Dilation_j',dilation_j)
cv.imshow('Dilation_3j',dilation_3j)


cv.waitKey(0)
cv.destroyAllWindows()

kernel
[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


## 嘗試更換另一張圖