# OpenCV-侵蝕 (Erosion)

## j範例

<table>
    <tr>
        <td><img src="./img/J_with_white_noise.png"></td>
        <td> <img src="./img/J_with_black_noise.png"></td>
    </tr>
</table>

In [3]:
import cv2 as cv
import numpy as np

In [8]:
img_j = cv.imread('./img/J_with_white_noise.png')#讀取影像
#img_j = cv.imread('./img/j_with_black_noise.png')#讀取影像

In [12]:
kernel = np.ones((5,5),np.float32)/25
print("kernel")
print(kernel)

erosion_j = cv.erode(img_j,kernel,iterations = 1)
erosion_2j = cv.erode(img_j,kernel,iterations = 2)
#dst_img=cv.erode(src_img,kernel,iterations)
#dst_img:輸出影像
#src_img:輸入影像
#kernel:使用的核
#iterations:跌代次數

#顯示影像處理結果
cv.imshow('Ori_j',img_j)
cv.imshow('Erosion_j',erosion_j)
cv.imshow('Erosion_2j',erosion_2j)


cv.waitKey(0)
cv.destroyAllWindows()

kernel
[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


## 嘗試更換另一張圖