## key 範例

In [1]:
import cv2 as cv
import numpy as np

In [4]:
img_key= cv.imread('./img/key_with_Salt_noise.png')#讀取影像

In [5]:
kernel = np.ones((3,3),np.float32)/25
print(kernel)

erosion_key = cv.erode(img_key , kernel , iterations = 1)
erosion_2key = cv.erode(img_key , kernel , iterations = 2)

cv.imshow('Ori_key',img_key)
cv.imshow('Erosion_key',erosion_key)
cv.imshow('Erosion_key',erosion_2key)


cv.waitKey(0)
cv.destroyAllWindows()


[[0.04 0.04 0.04]
 [0.04 0.04 0.04]
 [0.04 0.04 0.04]]
