# OpenCV-侵蝕 (Erosion)

## lenna 範例

In [5]:
import cv2 as cv
import numpy as np

In [6]:
img_lenna = cv.imread('./img/lenna.png')
#img_lenna = cv.imread('./img/lenna_with_Salt-and-pepper_noise.png')#讀取影像

In [7]:
kernel = np.ones((5,5),np.float32)/25
print("kernel")
print(kernel)

erosion_lenna = cv.erode(img_lenna,kernel,iterations = 1)
erosion_2lenna = cv.erode(img_lenna,kernel,iterations = 2)

cv.imshow('Ori_lenna',img_lenna)
cv.imshow('Erosion_lenna',erosion_lenna)
cv.imshow('Erosion_2lenna',erosion_2lenna)


cv.waitKey(0)
cv.destroyAllWindows()


kernel
[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]
