# 膨脹侵蝕進階範例 Advance example

## 交通號誌範例

In [9]:
import cv2 as cv
import numpy as np

In [10]:
#移動視窗函式(排版用)
def signMoveWindow():
    #移動視窗(排版用)
    window_location=[0,0]
    cv.moveWindow("Ori_Sign", window_location[0], window_location[1])
    window_location[0]+=img_sign.shape[1]
    cv.moveWindow("Gray_Sign", window_location[0], window_location[1])
    window_location[0]+=img_sign.shape[1]
    cv.moveWindow("Binary_Sign", window_location[0], window_location[1])
    window_location[1]+=img_sign.shape[0]+35
    window_location[0]=0
    cv.moveWindow("Dilation_Sign", window_location[0], window_location[1])
    window_location[0]+=img_sign.shape[1]
    cv.moveWindow("Dilation_Sign_2", window_location[0], window_location[1])
    window_location[1]+=img_sign.shape[0]+35
    window_location[0]=0
    cv.moveWindow("Erosion_Sign", window_location[0], window_location[1])
    window_location[0]+=img_sign.shape[1]
    cv.moveWindow("Erosion_Sign_3", window_location[0], window_location[1])
    window_location[1]+=img_sign.shape[0]+20
    window_location[0]=0

    
def lennaMoveWindow():
    #移動視窗(排版用)
    window_location=[0,0]
    cv.moveWindow("Ori_Lena", window_location[0], window_location[1])
    window_location[0]+=img_lena.shape[1]
    cv.moveWindow("Dilation_Lena", window_location[0], window_location[1])
    window_location[0]+=img_lena.shape[1]
    cv.moveWindow("Dilation_Lena_3", window_location[0], window_location[1])
    window_location[1]+=img_lena.shape[0]+35
    window_location[0]=0
    cv.moveWindow("Erosion_Lena", window_location[0], window_location[1])
    window_location[0]+=img_lena.shape[1]
    cv.moveWindow("Erosion_Lena_5", window_location[0], window_location[1])

In [11]:
kernel = np.ones((5,5),np.float32)/25
print(kernel)

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


In [21]:
#===========================膨脹===============================#

#讀取圖檔
img_sign = cv.imread('./img/Traffic_sign0.jpg')
gray_sign = cv.cvtColor(img_sign, cv.COLOR_BGR2GRAY)
ret, binary_sign = cv.threshold(gray_sign,127,255,cv.THRESH_BINARY_INV)

#iterations為膨脹的次數，下面將圖片分別膨脹一次和兩次，我們可以觀察其中的差別
dilation_sign = cv.dilate(binary_sign,kernel,iterations = 1)
dilation_sign2 = cv.dilate(binary_sign,kernel,iterations = 2)

#顯示影像處理前後結果
cv.imshow('Ori_Sign', img_sign)
cv.imshow('Gray_Sign', gray_sign)
cv.imshow('Binary_Sign', binary_sign)

cv.imshow('Dilation_Sign', dilation_sign)
cv.imshow('Dilation_Sign_2', dilation_sign2)

#===========================侵蝕===============================#

#iterations為侵蝕的次數，下面將圖片分別侵蝕一次和三次，我們可以觀察其中的差別
erosion_sign = cv.erode(binary_sign,kernel,iterations = 1)
erosion_sign3 = cv.erode(binary_sign,kernel,iterations = 3)

#顯示影像處理前後結果
cv.imshow('Erosion_Sign',erosion_sign)
cv.imshow('Erosion_Sign_3',erosion_sign3)

signMoveWindow()


cv.waitKey(0)
cv.destroyAllWindows()

## lenna 範例

In [22]:
#===========================膨脹===============================#
#讀取圖檔
img_lena = cv.imread('./img/lenna.png')

#iterations為膨脹的次數，下面將Lena分別膨脹一次和三次，我們可以觀察其中的差別
dilation_lena = cv.dilate(img_lena,kernel,iterations = 1)
dilation_lena3 = cv.dilate(img_lena,kernel,iterations = 3)

cv.imshow('Ori_Lena',img_lena)
cv.imshow('Dilation_Lena',dilation_lena)
cv.imshow('Dilation_Lena_3',dilation_lena3)

#===========================侵蝕===============================#

#iterations為侵蝕的次數，下面將Lena分別侵蝕一次和五次，我們可以觀察其中的差別
erosion_lena = cv.erode(img_lena,kernel,iterations = 1)
erosion_lena5 = cv.erode(img_lena,kernel,iterations = 5)

cv.imshow('Erosion_Lena',erosion_lena)
cv.imshow('Erosion_Lena_5',erosion_lena5)



lennaMoveWindow()


cv.waitKey(0)
cv.destroyAllWindows()