# Opencv-斷開 (Opening)

In [2]:
import cv2 as cv
import numpy as np

In [11]:
#讀取範例圖片（這邊的範例圖片請選擇opening_sample.png）
img_opening = cv.imread('./img/j_with_white_noise.png')

#img_opening = cv.imread('./img/j_with_black_noise.png')

In [12]:
kernel = np.ones((5,5),np.float32)/25

print("kernel")
print(kernel)

#使用opencv內建opening函式做影像處理
opening_j = cv.morphologyEx(img_opening, cv.MORPH_OPEN, kernel)
#dst_img=cv.morphologyEx(src_img,cv.MORPH_OPEN,kernel)
#dst_img:輸出影像
#src_img:輸入影像
#cv.MORPH_OPEN 使用本函式做斷開處理
#kernel:使用的核



#顯示影像處理結果
cv.imshow('ori_j',img_opening)
cv.imshow('opening_j',opening_j)

cv.waitKey(0)
cv.destroyAllWindows()

kernel
[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]
