# OpenCV-閉合(Closing)

In [11]:
import cv2 as cv
import numpy as np

In [45]:
#讀取範例圖片（這邊的範例圖片請選擇opening_sample.png）
img_closing = cv.imread('./img/j_with_white_noise.png')
img_closing = cv.imread('./img/open.png')
#img_closing = cv.imread('./img/geometry.png')
#img_closing = cv.imread('./img/j_with_black_noise.png')

In [52]:
kernel = np.ones((3,3),np.float32)

print("kernel")
print(kernel)

#使用opencv內建opening函式做影像處理
#closing_j = cv.morphologyEx(img_closing, cv.MORPH_CLOSE, kernel,iterations=10)
closing_j = cv.morphologyEx(img_closing, cv.MORPH_OPEN, kernel,iterations=5)
#dst_img=cv.morphologyEx(src_img,cv.MORPH_OPEN,kernel)
#dst_img:輸出影像
#src_img:輸入影像
#cv.MORPH_CLOSE 使用本函式做斷開處理
#kernel:使用的核




#顯示影像處理結果
cv.imshow('ori_j',img_closing)
cv.imshow('closing_j',closing_j)

cv.waitKey(0)
cv.destroyAllWindows()

kernel
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
